camunda-rest:
  url: ${CAMUNDA_REST_URL:https://digibp.herokuapp.com/rest}
  tenantid: ${CAMUNDA_TENANT_ID:showcase}

spring:
  profiles:
    active: local
  cloud:
    stream:
      bindings:
        output-insurance-mailing:
          destination: insurance-mailing
          content-type: application/json
          group: insurance-mailing-group
        output-insurance-mdm:
          destination: insurance-mdm
          content-type: application/json
          group: insurance-mdm-group
      default-binder: rabbit